import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";

import "./globals.css";

import Sidebar from "@/components/layout/sidebar";
import Topbar from "@/components//layout/topbar";
import { Toaster } from "sonner";
import ClickPopEffect from "@/components/global/click-pop-effect";
import SidebarMobile from "@/components/layout/sidebar-mobile";

const bricolage = Bricolage_Grotesque({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Veda AI",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bricolage.className} antialiased bg-[#F9F9F9] text-[#2D2D2D]`}
      >
        <ClickPopEffect />
        <Toaster richColors />
        <div className="flex h-screen overflow-hidden">
          {/* Desktop Sidebar */}
          <div className="hidden lg:block p-4">
            <Sidebar />
          </div>

          {/* Mobile Sidebar */}
          <div className="lg:hidden">
            <SidebarMobile />
          </div>

          {/* Main Content */}
          <div className="flex-1 flex flex-col min-w-0">
            {/* Desktop Topbar */}
            <div className="hidden lg:block py-4 px-2">
              <Topbar />
            </div>

            {/* Dynamic Page Content */}
            <main className="flex-1 overflow-y-auto">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
