import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import ClickPopEffect from "@/components/global/click-pop-effect";
import AuthProvider from "@/components/global/auth-provider";
import LayoutWrapper from "@/components/global/layout-wrapper";

const bricolage = Bricolage_Grotesque({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Veda AI",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
    ${bricolage.className}
    antialiased
    text-[#2D2D2D]
    bg-[#CECECE]
    lg:bg-[#E2E2E2]
  `}
      >
        <ClickPopEffect />

        <Toaster richColors />

        <AuthProvider>
          <LayoutWrapper>{children}</LayoutWrapper>
        </AuthProvider>
      </body>
    </html>
  );
}
